### ISSUE TITLE
Issues about installation ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by Bio-MingChen** [Roshan1992/RedeFISH#2]
Hi, I am trying to install the package as steps of introduction,but after I set the environment , I run the redefish and get the conflict error like below,do you have any idea about it ? Thanks.
/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/__init__.py:143: UserWarning: A NumPy version >=1.19.5 and <1.27.0 is required for this version of SciPy (detected version 2.0.0)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/TJPROJ6/SC/personal_dir/chenming/research/cell_segmentation_for_spatial/scripts/redfish_test.py", line 1, in <module>
    import scanpy as sc
  File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scanpy/__init__.py", line 6, in <module>
    from ._utils import check_versions
  File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scanpy/_utils/__init__.py", line 20, in <module>
    from scipy import sparse
  File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/__init__.py", line 200, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/sparse/__init__.py", line 267, in <module>
    from ._csr import *
  File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/sparse/_csr.py", line 10, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/TJPROJ6/SC/personal_dir/chenming/research/cell_segmentation_for_spatial/scripts/redfish_test.py", line 1, in <module>
    import scanpy as sc
  File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scanpy/__init__.py", line 6, in <module>
    from ._utils import check_versions
  File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scanpy/_utils/__init__.py", line 20, in <module>
    from scipy import sparse
  File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/__init__.py", line 200, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/sparse/__init__.py", line 267, in <module>
    from ._csr import *
  File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/sparse/_csr.py", line 10, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: numpy.core.multiarray failed to import

**Comment by Liyongheng-03** [comment]
> Hi, I am trying to install the package as steps of introduction,but after I set the environment , I run the redefish and get the conflict error like below,do you have any idea about it ? Thanks. /TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/**init**.py:143: UserWarning: A NumPy version >=1.19.5 and <1.27.0 is required for this version of SciPy (detected version 2.0.0) warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
> 
> A module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.0 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
> 
> If you are a user of the module, the easiest solution will be to downgrade to 'numpy<2' or try to upgrade the affected module. We expect that some modules will need time to support NumPy 2.
> 
> Traceback (most recent call last): File "/TJPROJ6/SC/personal_dir/chenming/research/cell_segmentation_for_spatial/scripts/redfish_test.py", line 1, in import scanpy as sc File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scanpy/**init**.py", line 6, in from ._utils import check_versions File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scanpy/_utils/**init**.py", line 20, in from scipy import sparse File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/**init**.py", line 200, in **getattr** return _importlib.import_module(f'scipy.{name}') File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/sparse/**init**.py", line 267, in from ._csr import * File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/sparse/_csr.py", line 10, in from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks, AttributeError: _ARRAY_API not found Traceback (most recent call last): File "/TJPROJ6/SC/personal_dir/chenming/research/cell_segmentation_for_spatial/scripts/redfish_test.py", line 1, in import scanpy as sc File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scanpy/**init**.py", line 6, in from ._utils import check_versions File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scanpy/_utils/**init**.py", line 20, in from scipy import sparse File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/**init**.py", line 200, in **getattr** return _importlib.import_module(f'scipy.{name}') File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/sparse/**init**.py", line 267, in from ._csr import * File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/sparse/_csr.py", line 10, in from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks, ImportError: numpy.core.multiarray failed to import

这是我的包的版本，其他的跟给出的要求保持一致
：
    - numpy==1.23.0
    - pandas==1.5.3
    - scikit-misc==0.1.4
    - scikit-learn==1.0.2
    - scanpy==1.9.3
    - Shapely==1.8.5
    - alphashape==1.3.1
    目前运行example.ipynb是没问题的，你可以参考一下

**Comment by Roshan1992** [comment]
好的，谢谢您的反馈！看上去是scipy的版本过高导致的？我自己的是scipy&nbsp;1.10.1可行。


不过要是example.ipynb能正常运行，那就应该是可以正常运行的环境了？


Cheers
Yunshan




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Roshan1992/RedeFISH"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月6日(星期三) 晚上9:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Roshan1992/RedeFISH] Issues about installation ImportError: numpy.core.multiarray failed to import (Issue #2)





  
Hi, I am trying to install the package as steps of introduction,but after I set the environment , I run the redefish and get the conflict error like below,do you have any idea about it ? Thanks. /TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/init.py:143: UserWarning: A NumPy version &gt;=1.19.5 and <1.27.0 is required for this version of SciPy (detected version 2.0.0) warnings.warn(f"A NumPy version &gt;={np_minversion} and <{np_maxversion}"
 
A module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.0 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11&gt;=2.12'.
 
If you are a user of the module, the easiest solution will be to downgrade to 'numpy<2' or try to upgrade the affected module. We expect that some modules will need time to support NumPy 2.
 
Traceback (most recent call last): File "/TJPROJ6/SC/personal_dir/chenming/research/cell_segmentation_for_spatial/scripts/redfish_test.py", line 1, in import scanpy as sc File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scanpy/init.py", line 6, in from ._utils import check_versions File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scanpy/_utils/init.py", line 20, in from scipy import sparse File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/init.py", line 200, in getattr return _importlib.import_module(f'scipy.{name}') File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/importlib/init.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/sparse/init.py", line 267, in from ._csr import * File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/sparse/_csr.py", line 10, in from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks, AttributeError: _ARRAY_API not found Traceback (most recent call last): File "/TJPROJ6/SC/personal_dir/chenming/research/cell_segmentation_for_spatial/scripts/redfish_test.py", line 1, in import scanpy as sc File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scanpy/init.py", line 6, in from ._utils import check_versions File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scanpy/_utils/init.py", line 20, in from scipy import sparse File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/init.py", line 200, in getattr return _importlib.import_module(f'scipy.{name}') File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/importlib/init.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/sparse/init.py", line 267, in from ._csr import * File "/TJPROJ6/SC/personal_dir/chenming/software/Miniconda/miniconda202012/envs/RedeFISH_env/lib/python3.9/site-packages/scipy/sparse/_csr.py", line 10, in from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks, ImportError: numpy.core.multiarray failed to import
  
这是我的包的版本，其他的跟给出的要求保持一致
 ：
 - numpy==1.23.0
 - pandas==1.5.3
 - scikit-misc==0.1.4
 - scikit-learn==1.0.2
 - scanpy==1.9.3
 - Shapely==1.8.5
 - alphashape==1.3.1
 目前运行example.ipynb是没问题的，你可以参考一下
